spring:
  application:
    name: captcha-demo


captcha:
  width: 200
  height: 100
  session:
    code: captchaCode
    date: captchaDate


logging:
  level:
    root: info
    com:
      wenbobi:
        captchademo: trace
  file:
    name: D:/java_code/Java_learning/captcha-demo/springboot.log
